### ISSUE TITLE
Яндекс.Практикум:Код-ревью

### ISSUE THREAD

**Issue by zlocate** [ustyuzhanina/sprint-10-validation#4]
Добрый вечер. Благодарю за проделанную работу.
К сожалению, текущая реализация содержит ряд недостатков не позволяющих мне засчитать ее на данной итерации:

## Репозиторий

**Можно лучше** интересное и содержательное README, браво! К сожалению несколько портит впечатление не совсем корректная разметка, а в частности излишнее использование заголовков (все описание полей и ограничений накладываемых на них выполнено в виде заголовков верхнего уровня из-за чего сливается)
Также рекомендую перенести ссылку из непосредственно заголовка под него, а в заголовке оставить непосредственно наименование проекта.

В дополнение к ссылкам из практики рекомендую почитать статью "Как написать хороший README?".

Ссылка на статью:
https://medium.com/astrolabe/%D0%BA%D0%B0%D0%BA-%D0%BD%D0%B0%D0%BF%D0%B8%D1%81%D0%B0%D1%82%D1%8C-%D1%85%D0%BE%D1%80%D0%BE%D1%88%D0%B8%D0%B9-readme-159f88076b26
Примеры шаблонов для README:
https://gist.github.com/PurpleBooth/109311bb0361f32d87a2,
https://gist.github.com/fvcproductions/1bfc2d4aecb01a834b46

### Имя
**Нужно исправить** следующие некорректные кейсы проходят валидацию
`МарияМ - в имени может быть только одна заглавная буква (точнее по одной заглавной на каждую часть имени, если оно двойное :) )

### Email
**Нужно исправить** следующие некорректные кейсы проходят валидацию
`@site.ru` - отсутствует имя пользователя (адрес ящика до @)
`_@site.ru` - имя ящика не может состоять только из спецсимволов
`_some_@ya.ru` - имя ящика не может начинаться и заканчиваться на спецсимвол
`test@.com` - отсутствует доменное имя
**Нужно исправить** следующие корректные кейсы не проходят валидацию
`some-extra-long-name@some.extra.long.domain.name` - адрес почты может быть произвольной длины, также как и число поддоменов.

#### Номер телефона

**Нужно исправить**: Данные форматы номеров телефонов проходят валидацию, хотя с точки зрения постановки задачи они являются невалидными.
```
+7(925 900-90-90
+7925900-90-90
+792590090-90
+7 (925) 900-90-90
+7 (925) 9009090
+7(925) 9009090
+7 (925)9009090
+7(925)9009090
+7 925 900-90-90
```

Адрес сайта
**Нужно исправить** следующие корректные кейсы не проходят валидацию
http://some.test.yandex.academy- адрес сайта может содержать произвольное количество поддоменов и длинную доменную зону

**Нужно исправить** следующие некорректные кейсы проходят валидацию
https://mysite.23 (tld не может состоять из цифр) 

**Можно лучше** следующие некорректные кейсы проходят валидацию
http://www.google.ru/////// (в пути количество слешей подряд должно быть ограничено 1)

**Comment by zlocate** [comment]
Добрый вечер. Работа принята.

**Comment by zlocate** [comment]
Вы впечатлили меня своим README. Браво! Плюс за кретивность. Также отмечу тщетельную проработку кейсов.
Желаю успехов в дальнейшем прохождении курса

**Comment by ustyuzhanina** [comment]
Спасибо за ревью! Решила сразу постараться довести до ума README, так как, насколько я понимаю, в современных реалиях это важный документ.
